// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "hello": "Hello, world!",
  "LocaleLayout": {
    "title": "next-intl example"
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, ru {🇷🇺 Русский} en {🇺🇸 Английский} other {Unknown}}"
  },
  "Manifest": {
    "name": "next-intl example"
  },
  "pathnamesPage": {
    "description": "<p>The pathnames are internationalized too.</p><p>If you're using the default language English, you'll see <code>/en/pathnames</code> in the browser address bar on this page.</p><p>If you change the locale to Russian, the URL is localized accordingly (<code>ru/путь</code>).</p>",
    "title": "Pathnames"
  },
  "Navigation": {
    "home": "Home",
    "pathnames": "Pathnames"
  },
  "indexPage": {
    "description": "This is a basic example that demonstrates the usage of <code>next-intl</code> with the Next.js App Router. Try changing the locale in the top right corner and see how the content changes.",
    "title": "next-intl example"
  }
};
export default messages;